# Generated by Django 5.1 on 2024-09-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='poste',
            new_name='poster',
        ),
    ]
