# Generated by Django 5.1 on 2024-09-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_poste_courselist_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='duration',
            new_name='duration_months',
        ),
        migrations.AddField(
            model_name='courselist',
            name='duration_years',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
