# Generated by Django 5.1 on 2024-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_alter_courselist_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='videos/'),
        ),
    ]
