# Generated by Django 5.1 on 2024-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_courselist_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='poster',
            new_name='poster_local',
        ),
        migrations.AddField(
            model_name='courselist',
            name='poster_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='duration_months',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='duration_years',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
